---
title: "Association of RE scores and a campus's involvement in the RE TWG: Grade 8"
author: "Joseph S. Tabadero, Jr."
date: "November 1, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, message = F, fig.height = 7, fight.width = 12, ggplot2::theme_set(ggplot2::theme_bw()), out.width = "55%", fig.align = "center")
```

## Data

```{r}
source("re_data_structuring.R")
```

```{r}
twg <- fread("./Data/processed/twg.csv", na = "")
colnames(twg) <- tolower(colnames(twg))
twg <- twg %>%
  mutate(subject = tolower(case_when(subject %in% c("integrated", "Integrated", "Integrated Science")~"is",
                             subject == "Mathematics"~"math",
                             subject == "Biology"~"bio",
                             subject == "Chemistry"~"chem",
                             subject == "Physics"~"phys",
                             subject == "Social Science"~"ss",
                             subject == "Statistics"~"stat",
                             TRUE~subject))) %>%
  mutate(grade = as.integer(str_extract_all(grade, "[0-9]+"))) %>%
  mutate(campus = str_remove_all(campus, "PSHS-"))
```

```{r}
retwg <- left_join(re2015_18, twg, by = c("campus", "year", "subject")) %>%
  rename(grade = grade.x) %>% filter(assessment == "re")
retwg <- retwg %>%
  mutate(withtwg = case_when(
    (year %in% c("2015", "2016")) & !is.na(name)~"with twg",
    (year %in% c("2015", "2016")) & is.na(name)~"no twg",
    (year %in% c("2017", "2018")) & is.na(name)~"no twg",
    TRUE ~ twg,
    )) %>%
  mutate(withtwg2 = case_when(
    !is.na(name)~"with twg",
    TRUE~"no twg"
  )
           ) %>%
  mutate(pct = round(score / maxscore * 100, 2))
```

## Grade 8 System-wide MCQ Scoress

### 2018

```{r, fig.height=4}
retwg %>% filter(test_type == "mcq", grade == "8", year == "2018") %>%
  ggplot(aes(withtwg2, pct)) + geom_boxplot() +
  facet_wrap(~grade + subject, ncol = 5)
```

### 2017

```{r, fig.height=4}
retwg %>% filter(test_type == "mcq", grade == "8", year == "2017") %>%
  ggplot(aes(withtwg2, pct)) + geom_boxplot() +
  facet_wrap(~grade + subject, ncol = 5)
```

### 2016

```{r, fig.height=4}
retwg %>% filter(test_type == "mcq", grade == "8", year == "2016") %>%
  ggplot(aes(withtwg2, pct)) + geom_boxplot() +
  facet_wrap(~grade + subject, ncol = 5)
```

### 2015

```{r, fig.height=4}
retwg %>% filter(test_type == "mcq", grade == "8", year == "2015") %>%
  ggplot(aes(withtwg2, pct)) + geom_boxplot() +
  facet_wrap(~grade + subject, ncol = 5)
```









## Grade 8 Social Science MCQ Scores

### 2018

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "ss", grade == "8", year == "2018") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2017

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "ss", grade == "8", year == "2017") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2016

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "ss", grade == "8", year == "2016") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```
### 2015

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "ss", grade == "8", year == "2015") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```
## Grade 8 English MCQ Scores

### 2018

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "english", grade == "8", year == "2018") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```


### 2017

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "english", grade == "8", year == "2017") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2016

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "english", grade == "8", year == "2016") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2015

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "english", grade == "8", year == "2015") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```
## Grade 8 Filipino MCQ Scores

### 2018

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "english", grade == "8", year == "2018") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```


### 2017

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "filipino", grade == "8", year == "2017") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```


### 2016

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "filipino", grade == "8", year == "2016") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2015

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "filipino", grade == "8", year == "2015") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

## Grade 8 Mathematics MCQ Scores

### 2018

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "math", grade == "8", year == "2018") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip()  + scale_fill_brewer(palette="Greys")
```

### 2017

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "math", grade == "8", year == "2017") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```



### 2016

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "math", grade == "8", year == "2016") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```




### 2015

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "mcq", subject == "math", grade == "8", year == "2015") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```



## Grade 8 System-wide Non-MCQ Scoress

### 2018

```{r, fig.height=4}
retwg %>% filter(test_type == "non-mcq", grade == "8", year == "2018") %>%
  ggplot(aes(withtwg2, pct)) + geom_boxplot() +
  facet_wrap(~grade + subject, ncol = 5) + scale_fill_brewer(palette="Greys")
```

### 2017

```{r, fig.height=4}
retwg %>% filter(test_type == "non-mcq", grade == "8", year == "2017") %>%
  ggplot(aes(withtwg2, pct)) + geom_boxplot() +
  facet_wrap(~grade + subject, ncol = 5)
```

### 2016

```{r, fig.height=4}
retwg %>% filter(test_type == "non-mcq", grade == "8", year == "2016") %>%
  ggplot(aes(withtwg, pct)) + geom_boxplot() +
  facet_wrap(~grade + subject, ncol = 5)
```


### 2016

```{r, fig.height=4}
retwg %>% filter(test_type == "non-mcq", grade == "8", year == "2015") %>%
  ggplot(aes(withtwg, pct)) + geom_boxplot() +
  facet_wrap(~grade + subject, ncol = 5)
```





## Grade 8 Social Science non-MCQ Scores

### 2018

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "ss", grade == "8", year == "2018") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2017

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "ss", grade == "8", year == "2017") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2016

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "ss", grade == "8", year == "2016") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2015

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "ss", grade == "8", year == "2015") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

## Grade 8 English non-MCQ Scores

### 2018

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "english", grade == "8", year == "2018") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```


### 2017

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "english", grade == "8", year == "2017") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2016

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "english", grade == "8", year == "2016") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2015

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "english", grade == "8", year == "2015") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

## Grade 8 Filipino non-MCQ Scores

### 2018

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "english", grade == "8", year == "2018") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```


### 2017

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "filipino", grade == "8", year == "2017") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```


### 2016

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "filipino", grade == "8", year == "2016") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() +scale_fill_brewer(palette="Greys")
```

### 2015

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "filipino", grade == "8", year == "2015") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() +scale_fill_brewer(palette="Greys")
```

## Grade 8 Mathematics non-MCQ Scores

### 2018

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "math", grade == "8", year == "2018") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```

### 2017

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "math", grade == "8", year == "2017") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```



### 2016

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "math", grade == "8", year == "2016") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```


### 2015

```{r, fig.height=3, fig.width=5}
retwg %>% filter(test_type == "non-mcq", subject == "math", grade == "8", year == "2015") %>%
  group_by(campus) %>%
  mutate(mean = mean(pct)) %>%
  ungroup() %>%
  mutate(campus = fct_reorder(campus, mean, .desc = TRUE)) %>%
  ggplot(aes(campus, pct, fill = withtwg)) + geom_boxplot() +
  coord_flip() + scale_fill_brewer(palette="Greys")
```